### ISSUE TITLE
Hide httpCalls Table

### ISSUE THREAD

**Issue by fongandrew** [xolvio/meteor-http-interceptor#2]
Is there an easy way to toggle the httpCalls table on and off? It blocks interaction with the elements underneath it and is visually distracting.

**Comment by SamHatoum** [comment]
The quickest way would be to add a CSS class override. I'll make this better in a future version

**Comment by SamHatoum** [comment]
this is now hidden by default, you can set a session var to enable it:

`httpInterceptorEnabled`
