### ISSUE TITLE
Interceptor cannot ignore certain URLs

### ISSUE THREAD

**Issue by fongandrew** [xolvio/meteor-http-interceptor#4]
Ignore functionality does not appear to be documented, but noticed it when poking through the source. Currently, the following code doesn't do anything.

``` javascript
var HttpInterceptor = Package['xolvio:http-interceptor'].HttpInterceptor;
HttpInterceptor.ignore(new RegExp("http://localhost:9200"));
```

I think the issue is at https://github.com/xolvio/meteor-http-interceptor/blob/master/server.js#L138-L140. Specifically, `!_shouldRecord` should be `!_shouldRecord(url)`

**Comment by SamHatoum** [comment]
Good spot, thanks!
